sudo: required
services:
        - docker

before:
        - docker build -t tomaszklawa/react_frontend -f Dockerfile.dev

script:
        - docker run -e CI=true tomaszklawa/react_frontend npm run test -- --coverage
